### PR TITLE
Update firedragon.cfg

### PR DESCRIPTION
**Pull request by enamulhasanabid**
- Updated prefs with respect to librewolf.cfg version 8.5

- Some prefs are not applicable with current version, added those for easy compare or merging in future. Those prefs doesn't create any issue in current browser stability and performance.

### CODE REVIEW

**Comment by dr460nf1r3** [comment]
As OP couldn't create a GitLab account, I encouraged them to send the PR here. While this is a read-only mirror, I'd manually pull and push the changed files to our GitLab repo for this single case. So, please don't merge, yet :D

**Comment by FGD-Garuda** [comment]
Changes have been walked through.
We are now moving into testing phase, nothing deep, just normal usage to make sure nothing obvious isn't working as expected.

**Comment by FGD-Garuda** [comment]
Hi @enamulhasanabid , most of your PR has been merged in our [gitlab repo](https://gitlab.com/garuda-linux/firedragon/settings/-/commit/b22a707a82d9e2a881e106ac93573fc37ba65c72). Thank you for bringing those up!

4 settings where not implemented:

1. `defaultPref("browser.formfill.enable", false);` was left aside because we want to keep more user usability than Librewolf and we believe the security risk on this one is low.
2. `defaultPref("browser.safebrowsing.allowOverride", false);` was left aside because we need this one to be enabled as we assume users are responsible and if they really need to override the warning we want to give them the possibility.
3. `defaultPref("browser.download.start_downloads_in_tmp_dir", true);` was left aside because we want files to be downloaded to the Downloads folder, not a temporary folder somewhere, potentially causing confusion for the user. We think the security risk is very low on this one.
4. `defaultPref("extensions.quarantinedDomains.enabled", false);` was left aside because it is supposed to be removed with v116+ and we are at v128. This one might get revisited, as myself could not find that UI...

**Comment by stefanwimmer128** [comment]
Looks good to me. Merged it into builder and preparing next release (v11.19.1-2).

**Pull request closed without merging**
